/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.LogManager;
import javax.swing.JList;
import javax.swing.JScrollPane;
import source.CatCellEditor;
import source.Data;
import source.DateUtil;
import source.MyTableModel;
import source.Operator;
import source.ReadAndWrite;
import source.SubCatCellEditor;

/**
 *
 * @author valery.titov
 */
public class MainFrame extends javax.swing.JFrame {
    private static Operator op;
    private static final int LAST_COSTS = 40;
    private static final String FNAME = "Cost.data";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        op = new Operator(new ReadAndWrite(FNAME).read());
        initComponents();
    }
    public void refresh() {
        lastCostsArea.setText(op.getLastCosts(LAST_COSTS));
        lastMontsCostsField.setText(op.getLastMonthSum());
        lastYearCostsField.setText(op.getLastYearMonthSum());
        thisMonthCostsField.setText(op.getThisMonthSum());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        DateFormat df = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT, Locale.getDefault());
        dateField = new javax.swing.JFormattedTextField(df);
        commentField = new javax.swing.JTextField();
        alarmLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cathegoryList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        subCathegoryList = new javax.swing.JList();
        NumberFormat nf = NumberFormat.getInstance(Locale.getDefault());
        nf.setMaximumFractionDigits(2);
        nf.setMinimumFractionDigits(2);
        costField = new javax.swing.JFormattedTextField(nf);
        confirmAddRow = new javax.swing.JButton();
        statTypeGroupButton1 = new javax.swing.ButtonGroup();
        statPeriodGroupButton1 = new javax.swing.ButtonGroup();
        statTypeGroupButton2 = new javax.swing.ButtonGroup();
        statPeriodGroupButton2 = new javax.swing.ButtonGroup();
        statPeriodGroupButton3 = new javax.swing.ButtonGroup();
        mainTabbedPane = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        majorNumStat = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lastCostsArea = new javax.swing.JTextArea();
        lastMontsCostsField = new javax.swing.JTextField();
        lastYearCostsField = new javax.swing.JTextField();
        thisMonthCostsField = new javax.swing.JTextField();
        statPanel1 = new javax.swing.JPanel();
        statTypePanel1 = new javax.swing.JPanel();
        subCathRButton1 = new javax.swing.JRadioButton();
        cathRButton1 = new javax.swing.JRadioButton();
        statPeriodPanel1 = new javax.swing.JPanel();
        yearRButton1 = new javax.swing.JRadioButton();
        monthRButton1 = new javax.swing.JRadioButton();
        monthComboBox1 = new javax.swing.JComboBox();
        yearSpinner1 = new javax.swing.JSpinner();
        refreshStatButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statArea1 = new javax.swing.JTextArea();
        statPanel2 = new javax.swing.JPanel();
        statPeriodPanel2 = new javax.swing.JPanel();
        yearRButton2 = new javax.swing.JRadioButton();
        monthRButton2 = new javax.swing.JRadioButton();
        refreshStatButton2 = new javax.swing.JButton();
        yearSpinner2 = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        statArea2 = new javax.swing.JTextArea();
        statTypePanel2 = new javax.swing.JPanel();
        subCathRButton2 = new javax.swing.JRadioButton();
        cathRButton2 = new javax.swing.JRadioButton();
        monthComboBox2 = new javax.swing.JComboBox();
        majorPlotStat = new javax.swing.JPanel();
        mainPlotPanel = new javax.swing.JPanel();
        circlePlotPanel1 = new CirclePlotPanel();
        legendPlotPanel1 = new LegendPlotPanel();
        plotButton = new javax.swing.JButton();
        statPeriodPanel3 = new javax.swing.JPanel();
        yearRButton3 = new javax.swing.JRadioButton();
        monthRButton3 = new javax.swing.JRadioButton();
        monthComboBox3 = new javax.swing.JComboBox();
        yearSpinner3 = new javax.swing.JSpinner();
        table = new javax.swing.JPanel();
        infoTableText = new javax.swing.JLabel();
        DateFormat dfTableTextField = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.getDefault());
        dateForTable = new javax.swing.JFormattedTextField(dfTableTextField);
        tableUpdate = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        tableCost = new javax.swing.JTable();
        summaryCost = new javax.swing.JLabel();
        addNewRow = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        deleteRowButton = new javax.swing.JButton();

        jFrame2.setTitle("Создание записи");
        jFrame2.setSize(new java.awt.Dimension(400, 480));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Введите данные записи"));

        dateField.setColumns(10);
        dateField.setToolTipText("Дата");
        dateField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        dateField.setValue(Calendar.getInstance().getTime());

        commentField.setColumns(30);
        commentField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        commentField.setToolTipText("Комментарий");

        alarmLabel.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        alarmLabel.setForeground(new java.awt.Color(255, 0, 0));

        cathegoryList.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        cathegoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = op.getAllCathegories();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        cathegoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cathegoryList.setToolTipText("Категории");
        cathegoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cathegoryListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(cathegoryList);
        cathegoryList.getAccessibleContext().setAccessibleName("");

        subCathegoryList.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        subCathegoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        subCathegoryList.setToolTipText("Подкатегории");
        subCathegoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                subCathegoryListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(subCathegoryList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        costField.setColumns(10);
        costField.setToolTipText("Цена");
        costField.setEnabled(false);
        costField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alarmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(commentField)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(costField)
                    .addComponent(alarmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        confirmAddRow.setText("Добавить");
        confirmAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(confirmAddRow)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmAddRow)
                .addContainerGap())
        );

        statTypeGroupButton1.add(cathRButton1);
        statTypeGroupButton1.add(subCathRButton1);
        statTypeGroupButton1.setSelected(cathRButton1.getModel(), true);

        statPeriodGroupButton1.add(yearRButton1);
        statPeriodGroupButton1.add(monthRButton1);
        statPeriodGroupButton1.setSelected(monthRButton1.getModel(), true);

        statTypeGroupButton2.add(cathRButton2);
        statTypeGroupButton2.add(subCathRButton2);
        statTypeGroupButton2.setSelected(cathRButton2.getModel(), true);

        statPeriodGroupButton2.add(yearRButton2);
        statPeriodGroupButton2.add(monthRButton2);
        statPeriodGroupButton2.setSelected(monthRButton2.getModel(), true);

        statPeriodGroupButton3.add(yearRButton3);
        statPeriodGroupButton3.add(monthRButton3);
        statPeriodGroupButton3.setSelected(monthRButton3.getModel(), true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Расходы");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Расходы"); // NOI18N
        setSize(new java.awt.Dimension(1000, 800));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });
        jTabbedPane3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane3FocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Последние расходы"));

        lastCostsArea.setEditable(false);
        lastCostsArea.setColumns(20);
        lastCostsArea.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        lastCostsArea.setRows(5);
        lastCostsArea.setText(op.getLastCosts(LAST_COSTS)
        );
        lastCostsArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastCostsAreaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lastCostsArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        lastMontsCostsField.setEditable(false);
        lastMontsCostsField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        lastMontsCostsField.setText(op.getLastMonthSum());
        lastMontsCostsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, DateUtil.getOnlyMonth(Calendar.getInstance().get(Calendar.MONTH) - 1).getDisplayName(Calendar.MONTH, Calendar.LONG_STANDALONE, Locale.getDefault()) 
            + " " + Integer.toString(Calendar.getInstance().get(Calendar.YEAR) - (Calendar.getInstance().get(Calendar.MONTH)==0?1:0)), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 11))); // NOI18N
    lastMontsCostsField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lastMontsCostsFieldActionPerformed(evt);
        }
    });

    lastYearCostsField.setEditable(false);
    lastYearCostsField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    lastYearCostsField.setText(op.getLastYearMonthSum());
    lastYearCostsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, Calendar.getInstance().getDisplayName(Calendar.MONTH, Calendar.LONG_STANDALONE, Locale.getDefault()) + " "
        + Integer.toString(Calendar.getInstance().get(Calendar.YEAR) - 1), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 11))); // NOI18N
lastYearCostsField.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        lastYearCostsFieldActionPerformed(evt);
    }
    });

    thisMonthCostsField.setEditable(false);
    thisMonthCostsField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    thisMonthCostsField.setText(op.getThisMonthSum());
    thisMonthCostsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, DateUtil.getOnlyMonth(Calendar.getInstance().get(Calendar.MONTH)).getDisplayName(Calendar.MONTH, Calendar.LONG_STANDALONE, Locale.getDefault()) 
        + " " + Integer.toString(Calendar.getInstance().get(Calendar.YEAR)), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 11))); // NOI18N

statPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Статистика 1"));

statTypePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Статистика по"));

subCathRButton1.setText("Подкатегориям");

cathRButton1.setText("Категориям");

javax.swing.GroupLayout statTypePanel1Layout = new javax.swing.GroupLayout(statTypePanel1);
statTypePanel1.setLayout(statTypePanel1Layout);
statTypePanel1Layout.setHorizontalGroup(
    statTypePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(statTypePanel1Layout.createSequentialGroup()
        .addComponent(cathRButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(subCathRButton1)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    statTypePanel1Layout.setVerticalGroup(
        statTypePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statTypePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(cathRButton1)
            .addComponent(subCathRButton1))
    );

    statPeriodPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Период"));

    yearRButton1.setText("Год");
    yearRButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            yearRButton1ActionPerformed(evt);
        }
    });

    monthRButton1.setText("Месяц");
    monthRButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            monthRButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout statPeriodPanel1Layout = new javax.swing.GroupLayout(statPeriodPanel1);
    statPeriodPanel1.setLayout(statPeriodPanel1Layout);
    statPeriodPanel1Layout.setHorizontalGroup(
        statPeriodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPeriodPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(monthRButton1)
            .addGap(18, 18, 18)
            .addComponent(yearRButton1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    statPeriodPanel1Layout.setVerticalGroup(
        statPeriodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPeriodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(monthRButton1)
            .addComponent(yearRButton1))
    );

    monthComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь" }));
    monthComboBox1.setToolTipText("Месяц");

    yearSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2015), null, null, Integer.valueOf(1)));
    yearSpinner1.setToolTipText("Год");

    refreshStatButton1.setText("Обновить");
    refreshStatButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            refreshStatButton1ActionPerformed(evt);
        }
    });

    statArea1.setEditable(false);
    statArea1.setColumns(15);
    statArea1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    statArea1.setRows(5);
    statArea1.setText(op.getStatisticCat(Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.YEAR))    );
    jScrollPane1.setViewportView(statArea1);

    javax.swing.GroupLayout statPanel1Layout = new javax.swing.GroupLayout(statPanel1);
    statPanel1.setLayout(statPanel1Layout);
    statPanel1Layout.setHorizontalGroup(
        statPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(statTypePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(statPeriodPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(statPanel1Layout.createSequentialGroup()
            .addComponent(monthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(yearSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(refreshStatButton1)
            .addGap(0, 32, Short.MAX_VALUE))
        .addComponent(jScrollPane1)
    );
    statPanel1Layout.setVerticalGroup(
        statPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPanel1Layout.createSequentialGroup()
            .addComponent(statTypePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(statPeriodPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(1, 1, 1)
            .addGroup(statPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(monthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(yearSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(refreshStatButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
    );

    monthComboBox1.setSelectedIndex(Calendar.getInstance().get(Calendar.MONTH));
    yearSpinner1.setValue(Calendar.getInstance().get(Calendar.YEAR));

    statPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Статистика 2"));

    statPeriodPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Период"));

    yearRButton2.setText("Год");
    yearRButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            yearRButton2ActionPerformed(evt);
        }
    });

    monthRButton2.setText("Месяц");
    monthRButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            monthRButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout statPeriodPanel2Layout = new javax.swing.GroupLayout(statPeriodPanel2);
    statPeriodPanel2.setLayout(statPeriodPanel2Layout);
    statPeriodPanel2Layout.setHorizontalGroup(
        statPeriodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPeriodPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(monthRButton2)
            .addGap(18, 18, 18)
            .addComponent(yearRButton2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    statPeriodPanel2Layout.setVerticalGroup(
        statPeriodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPeriodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(monthRButton2)
            .addComponent(yearRButton2))
    );

    refreshStatButton2.setText("Обновить");
    refreshStatButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            refreshStatButton2ActionPerformed(evt);
        }
    });

    yearSpinner2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2014), null, null, Integer.valueOf(1)));
    yearSpinner2.setToolTipText("Год");

    statArea2.setEditable(false);
    statArea2.setColumns(15);
    statArea2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    statArea2.setRows(5);
    statArea2.setText(op.getStatisticCat(Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.YEAR) - 1)    );
    jScrollPane5.setViewportView(statArea2);

    statTypePanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Статистика по"));

    subCathRButton2.setText("Подкатегориям");

    cathRButton2.setText("Категориям");

    javax.swing.GroupLayout statTypePanel2Layout = new javax.swing.GroupLayout(statTypePanel2);
    statTypePanel2.setLayout(statTypePanel2Layout);
    statTypePanel2Layout.setHorizontalGroup(
        statTypePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statTypePanel2Layout.createSequentialGroup()
            .addComponent(cathRButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(subCathRButton2)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    statTypePanel2Layout.setVerticalGroup(
        statTypePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statTypePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(cathRButton2)
            .addComponent(subCathRButton2))
    );

    monthComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь" }));
    monthComboBox2.setToolTipText("Месяц");

    javax.swing.GroupLayout statPanel2Layout = new javax.swing.GroupLayout(statPanel2);
    statPanel2.setLayout(statPanel2Layout);
    statPanel2Layout.setHorizontalGroup(
        statPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(statTypePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(statPeriodPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(statPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanel2Layout.createSequentialGroup()
                .addComponent(monthComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshStatButton2)))
    );
    statPanel2Layout.setVerticalGroup(
        statPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPanel2Layout.createSequentialGroup()
            .addComponent(statTypePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(5, 5, 5)
            .addComponent(statPeriodPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(1, 1, 1)
            .addGroup(statPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(monthComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(yearSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(refreshStatButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
    );

    yearSpinner2.setValue(Calendar.getInstance().get(Calendar.YEAR) - 1);
    monthComboBox2.setSelectedIndex(Calendar.getInstance().get(Calendar.MONTH));

    javax.swing.GroupLayout majorNumStatLayout = new javax.swing.GroupLayout(majorNumStat);
    majorNumStat.setLayout(majorNumStatLayout);
    majorNumStatLayout.setHorizontalGroup(
        majorNumStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(majorNumStatLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(majorNumStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(majorNumStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastMontsCostsField)
                    .addComponent(lastYearCostsField))
                .addComponent(thisMonthCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(statPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(statPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    majorNumStatLayout.setVerticalGroup(
        majorNumStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(majorNumStatLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(majorNumStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(statPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(majorNumStatLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(thisMonthCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lastMontsCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lastYearCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(statPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    jTabbedPane3.addTab("Цифры", majorNumStat);

    mainPlotPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

    int m = Calendar.getInstance().get(Calendar.MONTH);
    int y = Calendar.getInstance().get(Calendar.YEAR);
    circlePlotPanel1.setSegments(op.summaryFloatArray(op.getByMonth(m, y)));

    javax.swing.GroupLayout circlePlotPanel1Layout = new javax.swing.GroupLayout(circlePlotPanel1);
    circlePlotPanel1.setLayout(circlePlotPanel1Layout);
    circlePlotPanel1Layout.setHorizontalGroup(
        circlePlotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 400, Short.MAX_VALUE)
    );
    circlePlotPanel1Layout.setVerticalGroup(
        circlePlotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 400, Short.MAX_VALUE)
    );

    m = Calendar.getInstance().get(Calendar.MONTH);
    y = Calendar.getInstance().get(Calendar.YEAR);
    legendPlotPanel1.setList(op.legendText(op.getByMonth(m, y)));

    javax.swing.GroupLayout legendPlotPanel1Layout = new javax.swing.GroupLayout(legendPlotPanel1);
    legendPlotPanel1.setLayout(legendPlotPanel1Layout);
    legendPlotPanel1Layout.setHorizontalGroup(
        legendPlotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 382, Short.MAX_VALUE)
    );
    legendPlotPanel1Layout.setVerticalGroup(
        legendPlotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout mainPlotPanelLayout = new javax.swing.GroupLayout(mainPlotPanel);
    mainPlotPanel.setLayout(mainPlotPanelLayout);
    mainPlotPanelLayout.setHorizontalGroup(
        mainPlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPlotPanelLayout.createSequentialGroup()
            .addComponent(circlePlotPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(legendPlotPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    mainPlotPanelLayout.setVerticalGroup(
        mainPlotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(circlePlotPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(legendPlotPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    plotButton.setText("Построить");
    plotButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            plotButtonActionPerformed(evt);
        }
    });

    statPeriodPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Период"));

    yearRButton3.setText("Год");
    yearRButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            yearRButton3ActionPerformed(evt);
        }
    });

    monthRButton3.setText("Месяц");
    monthRButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            monthRButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout statPeriodPanel3Layout = new javax.swing.GroupLayout(statPeriodPanel3);
    statPeriodPanel3.setLayout(statPeriodPanel3Layout);
    statPeriodPanel3Layout.setHorizontalGroup(
        statPeriodPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPeriodPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(monthRButton3)
            .addGap(18, 18, 18)
            .addComponent(yearRButton3)
            .addContainerGap(22, Short.MAX_VALUE))
    );
    statPeriodPanel3Layout.setVerticalGroup(
        statPeriodPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(statPeriodPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(monthRButton3)
            .addComponent(yearRButton3))
    );

    monthComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь" }));
    monthComboBox3.setToolTipText("Месяц");

    yearSpinner3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2015), null, null, Integer.valueOf(1)));
    yearSpinner3.setToolTipText("Год");

    javax.swing.GroupLayout majorPlotStatLayout = new javax.swing.GroupLayout(majorPlotStat);
    majorPlotStat.setLayout(majorPlotStatLayout);
    majorPlotStatLayout.setHorizontalGroup(
        majorPlotStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(majorPlotStatLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(majorPlotStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plotButton)
                .addComponent(mainPlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(majorPlotStatLayout.createSequentialGroup()
                    .addComponent(monthComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(yearSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(statPeriodPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(156, Short.MAX_VALUE))
    );
    majorPlotStatLayout.setVerticalGroup(
        majorPlotStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(majorPlotStatLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(mainPlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(statPeriodPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(2, 2, 2)
            .addGroup(majorPlotStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(monthComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(yearSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(plotButton)
            .addContainerGap(147, Short.MAX_VALUE))
    );

    monthComboBox3.setSelectedIndex(Calendar.getInstance().get(Calendar.MONTH));
    yearSpinner3.setValue(Calendar.getInstance().get(Calendar.YEAR));

    jTabbedPane3.addTab("Графики", majorPlotStat);

    mainTabbedPane.addTab("Статистика", jTabbedPane3);

    infoTableText.setText("Выберите месяц");

    dateForTable.setColumns(10);
    dateForTable.setValue(Calendar.getInstance().getTime());

    tableUpdate.setText("Обновить");
    tableUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tableUpdateActionPerformed(evt);
        }
    });

    tableScrollPane.setName("Расходы"); // NOI18N

    tableCost.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Дата", "Категория", "Подкатегория", "Комментарий", "Цена"
        }
    ));
    tableScrollPane.setViewportView(tableCost);

    summaryCost.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

    javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
    table.setLayout(tableLayout);
    tableLayout.setHorizontalGroup(
        tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(tableLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(tableLayout.createSequentialGroup()
                    .addComponent(infoTableText)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dateForTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tableUpdate)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(summaryCost)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    tableLayout.setVerticalGroup(
        tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(tableLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(infoTableText)
                .addComponent(tableUpdate)
                .addComponent(dateForTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(summaryCost))
            .addGap(18, 18, 18)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
            .addContainerGap())
    );

    mainTabbedPane.addTab("Таблица", table);

    addNewRow.setText("Добавить запись");
    addNewRow.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addNewRowActionPerformed(evt);
        }
    });

    validateButton.setText("Проверить на ошибки");
    validateButton.setEnabled(false);
    validateButton.setFocusable(false);
    validateButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            validateButtonActionPerformed(evt);
        }
    });

    deleteRowButton.setText("Удалить запись");
    deleteRowButton.setEnabled(false);
    deleteRowButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            deleteRowButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(validateButton)
                    .addGap(242, 242, 242)
                    .addComponent(addNewRow)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteRowButton)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(mainTabbedPane)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(validateButton)
                .addComponent(addNewRow)
                .addComponent(deleteRowButton))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastMontsCostsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastMontsCostsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastMontsCostsFieldActionPerformed

    private void lastYearCostsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastYearCostsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastYearCostsFieldActionPerformed

    private void addNewRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowActionPerformed
        jFrame2.setVisible(true);
    }//GEN-LAST:event_addNewRowActionPerformed

    private void tableUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableUpdateActionPerformed
        Data d = op.getByMonthForTable((Date)dateForTable.getValue()).sortByDate(Data.SORT_ASC);
        MyTableModel model = new MyTableModel(d);
        tableCost.setModel(model);
        tableCost.getColumnModel().getColumn(1).setCellEditor(new CatCellEditor(d));
        tableCost.getColumnModel().getColumn(2).setCellEditor(new SubCatCellEditor(d));
        summaryCost.setText("Расходы за указанный месяц:   " + d.summary());
    }//GEN-LAST:event_tableUpdateActionPerformed

    private void confirmAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddRowActionPerformed
        Calendar c = new Calendar.Builder().setInstant((Date)dateField.getValue()).build();
        int cathegory = cathegoryList.getSelectedIndex() + 1;
        alarmLabel.setForeground(Color.red);
        if (cathegory == 0) { 
            alarmLabel.setText("Не указана категория"); 
            return; 
        }
        int subCathegory = subCathegoryList.getSelectedIndex() + 1;
        if (subCathegory == 0) { 
            alarmLabel.setText("Не указана подкатегория"); 
            return; 
        }
        Float cost = 0.0f;
        try {
            String s = costField.getValue().toString();
            cost = Float.parseFloat(s);
        } catch(NullPointerException e) {
            alarmLabel.setText("Не указана стоимость"); 
            return; 
        }
        String comment = "";
        try {
            comment = commentField.getText();
        } catch(NullPointerException e) { }
        op.addData(c, cathegory, subCathegory, cost, comment);
        alarmLabel.setForeground(Color.black);
        alarmLabel.setText("Запись успешно добавлена");
        
        //dateField.setValue(Calendar.getInstance().getTime());
        cathegoryList.clearSelection();
        subCathegoryList.clearSelection();
        costField.setValue(null);
        commentField.setText(null);
        refresh();
    }//GEN-LAST:event_confirmAddRowActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        refresh();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new ReadAndWrite(FNAME).write(op.getAll());
    }//GEN-LAST:event_formWindowClosing

    private void jTabbedPane3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane3FocusGained
        refresh();
    }//GEN-LAST:event_jTabbedPane3FocusGained

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        refresh();
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void mainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged
        refresh();
        if(mainTabbedPane.getSelectedIndex() == 1) deleteRowButton.setEnabled(true);
        else deleteRowButton.setEnabled(false);
    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        op.validate();
        refresh();
    }//GEN-LAST:event_validateButtonActionPerformed

    private void lastCostsAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastCostsAreaMouseClicked
        mainTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_lastCostsAreaMouseClicked

    private void deleteRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowButtonActionPerformed
        for (int i: tableCost.getSelectedRows()) {
            op.remove(op.getByMonthForTable((Date)dateForTable.getValue()).sortByDate(Data.SORT_ASC).get(i));
        }
        tableUpdateActionPerformed(evt);
    }//GEN-LAST:event_deleteRowButtonActionPerformed

    private void yearRButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearRButton1ActionPerformed
        monthComboBox1.setEnabled(false);
    }//GEN-LAST:event_yearRButton1ActionPerformed

    private void monthRButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthRButton1ActionPerformed
        monthComboBox1.setEnabled(true);
    }//GEN-LAST:event_monthRButton1ActionPerformed

    private void refreshStatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStatButton1ActionPerformed
        int i = (statTypeGroupButton1.isSelected(cathRButton1.getModel()) ? 0 : 2);
        i += (statPeriodGroupButton1.isSelected(monthRButton1.getModel()) ? 0 : 1);
        int month, year;
        month = monthComboBox1.getSelectedIndex();
        year = (Integer)yearSpinner1.getValue();
        switch (i) {
            case 0: statArea1.setText(op.getStatisticCat(month, year)); break;
            case 1: statArea1.setText(op.getStatisticCat(year)); break;
            case 2: statArea1.setText(op.getStatisticSubCat(month, year)); break;
            case 3: statArea1.setText(op.getStatisticSubCat(year)); break;
        }
    }//GEN-LAST:event_refreshStatButton1ActionPerformed

    private void yearRButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearRButton2ActionPerformed
        monthComboBox2.setEnabled(false);
    }//GEN-LAST:event_yearRButton2ActionPerformed

    private void monthRButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthRButton2ActionPerformed
        monthComboBox2.setEnabled(true);
    }//GEN-LAST:event_monthRButton2ActionPerformed

    private void refreshStatButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStatButton2ActionPerformed
        int i = (statTypeGroupButton2.isSelected(cathRButton2.getModel()) ? 0 : 2);
        i += (statPeriodGroupButton2.isSelected(monthRButton2.getModel()) ? 0 : 1);
        int month, year;
        month = monthComboBox2.getSelectedIndex();
        year = (Integer)yearSpinner2.getValue();
        switch (i) {
            case 0: statArea2.setText(op.getStatisticCat(month, year)); break;
            case 1: statArea2.setText(op.getStatisticCat(year)); break;
            case 2: statArea2.setText(op.getStatisticSubCat(month, year)); break;
            case 3: statArea2.setText(op.getStatisticSubCat(year)); break;
        }
        
    }//GEN-LAST:event_refreshStatButton2ActionPerformed

    private void plotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotButtonActionPerformed
        if (monthComboBox3.isEnabled()) {
            int m = monthComboBox3.getSelectedIndex();
            int y = (Integer)yearSpinner3.getValue();
            circlePlotPanel1.setSegments(op.summaryFloatArray(op.getByMonth(m, y)));
            legendPlotPanel1.setList(op.legendText(op.getByMonth(m, y)));
        } else {
            int y = (Integer)yearSpinner3.getValue();
            circlePlotPanel1.setSegments(op.summaryFloatArray(op.getByYear(y)));
            legendPlotPanel1.setList(op.legendText(op.getByYear(y)));
        }
        circlePlotPanel1.repaint();
        legendPlotPanel1.repaint();
    }//GEN-LAST:event_plotButtonActionPerformed

    private void cathegoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cathegoryListValueChanged
        if (((JList)evt.getSource()).getSelectedIndex() == -1) {
            subCathegoryList.setModel(new javax.swing.AbstractListModel() {
                String[] strings = {};
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
            });
            return;
        }
        subCathegoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = op.getAllSubCathegories(((JList)evt.getSource()).getSelectedIndex() + 1);
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_cathegoryListValueChanged

    private void subCathegoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_subCathegoryListValueChanged
        if (((JList)evt.getSource()).getSelectedIndex() >= 0) costField.setEnabled(true);
        else costField.setEnabled(false);
    }//GEN-LAST:event_subCathegoryListValueChanged

    private void yearRButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearRButton3ActionPerformed
        monthComboBox3.setEnabled(false);
    }//GEN-LAST:event_yearRButton3ActionPerformed

    private void monthRButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthRButton3ActionPerformed
        monthComboBox3.setEnabled(true);
    }//GEN-LAST:event_monthRButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try (FileInputStream in = new FileInputStream(new File("logging.properties"))){
            LogManager.getLogManager().readConfiguration(in); 
        } catch(IOException e) {
            System.err.println("Could not setup logger configuration: " + e.getMessage());
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewRow;
    private javax.swing.JLabel alarmLabel;
    private javax.swing.JRadioButton cathRButton1;
    private javax.swing.JRadioButton cathRButton2;
    private javax.swing.JList cathegoryList;
    private CirclePlotPanel circlePlotPanel1;
    private javax.swing.JTextField commentField;
    private javax.swing.JButton confirmAddRow;
    private javax.swing.JFormattedTextField costField;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JFormattedTextField dateForTable;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JLabel infoTableText;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea lastCostsArea;
    private javax.swing.JTextField lastMontsCostsField;
    private javax.swing.JTextField lastYearCostsField;
    private LegendPlotPanel legendPlotPanel1;
    private javax.swing.JPanel mainPlotPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel majorNumStat;
    private javax.swing.JPanel majorPlotStat;
    private javax.swing.JComboBox monthComboBox1;
    private javax.swing.JComboBox monthComboBox2;
    private javax.swing.JComboBox monthComboBox3;
    private javax.swing.JRadioButton monthRButton1;
    private javax.swing.JRadioButton monthRButton2;
    private javax.swing.JRadioButton monthRButton3;
    private javax.swing.JButton plotButton;
    private javax.swing.JButton refreshStatButton1;
    private javax.swing.JButton refreshStatButton2;
    private javax.swing.JTextArea statArea1;
    private javax.swing.JTextArea statArea2;
    private javax.swing.JPanel statPanel1;
    private javax.swing.JPanel statPanel2;
    private javax.swing.ButtonGroup statPeriodGroupButton1;
    private javax.swing.ButtonGroup statPeriodGroupButton2;
    private javax.swing.ButtonGroup statPeriodGroupButton3;
    private javax.swing.JPanel statPeriodPanel1;
    private javax.swing.JPanel statPeriodPanel2;
    private javax.swing.JPanel statPeriodPanel3;
    private javax.swing.ButtonGroup statTypeGroupButton1;
    private javax.swing.ButtonGroup statTypeGroupButton2;
    private javax.swing.JPanel statTypePanel1;
    private javax.swing.JPanel statTypePanel2;
    private javax.swing.JRadioButton subCathRButton1;
    private javax.swing.JRadioButton subCathRButton2;
    private javax.swing.JList subCathegoryList;
    private javax.swing.JLabel summaryCost;
    private javax.swing.JPanel table;
    private javax.swing.JTable tableCost;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton tableUpdate;
    private javax.swing.JTextField thisMonthCostsField;
    private javax.swing.JButton validateButton;
    private javax.swing.JRadioButton yearRButton1;
    private javax.swing.JRadioButton yearRButton2;
    private javax.swing.JRadioButton yearRButton3;
    private javax.swing.JSpinner yearSpinner1;
    private javax.swing.JSpinner yearSpinner2;
    private javax.swing.JSpinner yearSpinner3;
    // End of variables declaration//GEN-END:variables
}
